### ISSUE TITLE
apk无法使用

### ISSUE THREAD

**Issue by aaawzh** [s0urcelab/remote-helper#1]
您好 不知道为什么我使用不了这个apk 希望您可以帮助我

**Comment by s0urcelab** [comment]
详细一点的问题描述？

**Comment by aaawzh** [comment]
安装之后主界面没有这个app 
在ES管理里面启动不了
![Uploading Screenshot_20221021-111742.png…]()

**Comment by aaawzh** [comment]
> 

![Screenshot_20221021-111933](https://user-images.githubusercontent.com/116295265/197103756-eb6c72c7-b7db-4fd6-8c5a-eb8735e2e9f2.png)

**Comment by aaawzh** [comment]
安装之后主界面找不到 启动不了

**Comment by s0urcelab** [comment]
因为是快捷菜单用的，所以主入口隐藏了。
在快捷菜单里长按就能打开主界面了。

**Comment by aaawzh** [comment]
好的谢谢 明白了&nbsp;
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月21日(星期五) 下午3:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [s0urcelab/remote-helper] apk无法使用 (Issue #1)





 
因为是快捷菜单用的，所以主入口隐藏了。
 在快捷菜单里长按就能打开主界面了。
 
&mdash;
